/**
 * TD(λ) value network "bonus": v1's features plus an explicit bonus-economy
 * block — the "reward chasing" hypothesis.
 *
 * v1's encoding already carries group completion fractions, but the net must
 * derive the cascade structure itself: which bonus a group grants, how close
 * each printed bonus is to firing, and how productive the bonus engine has
 * been so far. This variant spells those out so they are linearly visible:
 *
 *  - 2: lifetime action-bar unlocks (reroll, +1), /7 — bonus production to
 *    date, invisible in v1 which only sees the *unspent* counters.
 *  - 1: completed bonus-carrying groups, /12.
 *  - 8: "one-away" counts per bonus kind — groups exactly one cell from
 *    firing, the cascade trigger signal (capped at 2, /2). Kind channels:
 *    reroll, +1, fox, X-yellow, X-blue, X-green, write-orange, write-purple.
 *  - 8: write-track "pull" per bonus kind — Σ 1/(1+d) over bonus-carrying
 *    slots at distance d from each track's next fill (capped at 1).
 *
 * 19 extra features, 182 total. Everything else (net shape, afterstate-argmax
 * policy, terminal handling) mirrors v1; MLP code is imported unchanged.
 * Weights live in tdnet-bonus-weights.ts (generated by the parallel trainer
 * with --features v1bonus).
 */
import {
  applyAction,
  getPending,
  scoreState,
  type Action,
  type Effect,
  type GameState,
  type VariantDef,
} from '../engine';
import type { Strategy } from './types';
import {
  createEvalCtx,
  extractFeatures,
  forward,
  netFromParams,
  TD_FEATURES,
  type EvalCtx,
  type TdNetParams,
} from './tdnet';
import { TDNET_BONUS_WEIGHTS } from './tdnet-bonus-weights';

// ---------------------------------------------------------------------------
// Feature extraction
// ---------------------------------------------------------------------------

/** v1's 163 features + 2 banked + 1 completed + 8 one-away + 8 track pull. */
export const TD_BONUS_FEATURES = TD_FEATURES + 19;

/** Bonus-kind channel of an effect, or -1 if untracked. */
function kindOf(e: Effect): number {
  switch (e.t) {
    case 'reroll':
      return 0;
    case 'plus1':
      return 1;
    case 'fox':
      return 2;
    case 'crossAny':
    case 'crossNext':
      return e.area === 'yellow' ? 3 : e.area === 'blue' ? 4 : 5;
    case 'writeNext':
      return e.area === 'orange' ? 6 : 7;
    default:
      return -1;
  }
}

/**
 * Encode a state into `x` (length TD_BONUS_FEATURES). The first TD_FEATURES
 * slots are exactly v1's encoding; the bonus-economy block follows.
 */
export function extractFeaturesBonus(s: GameState, v: VariantDef, x: Float64Array): void {
  extractFeatures(s, v, x); // zero-fills the whole buffer, writes [0, TD_FEATURES)
  const k = TD_FEATURES;

  x[k] = Math.min(7, s.barUnlocks.reroll) / 7;
  x[k + 1] = Math.min(7, s.barUnlocks.plus1) / 7;

  let completed = 0;
  const oneAway = k + 3;
  const pull = k + 11;
  for (const area of v.areas) {
    const cells = s.areas[area.id];
    const ui = area.ui;

    if (ui.groups) {
      for (const g of ui.groups) {
        if (!g.bonus) continue;
        const kind = kindOf(g.bonus);
        if (kind < 0) continue;
        let done = 0;
        for (const c of g.cells) if (cells[c] !== 0) done++;
        if (done === g.cells.length) completed++;
        else if (done === g.cells.length - 1) x[oneAway + kind] = Math.min(1, x[oneAway + kind] + 0.5);
      }
    }

    if (ui.kind === 'track') {
      const next = cells.findIndex((c) => c === 0);
      if (next < 0) continue;
      for (let i = next; i < ui.cells.length; i++) {
        const b = ui.cells[i].bonus;
        if (!b) continue;
        const kind = kindOf(b);
        if (kind < 0) continue;
        x[pull + kind] = Math.min(1, x[pull + kind] + 1 / (1 + (i - next)));
      }
    }
  }
  x[k + 2] = Math.min(12, completed) / 12;
}

// ---------------------------------------------------------------------------
// v1bonus3: landing-value features (from the bonus-graph analysis)
// ---------------------------------------------------------------------------

/**
 * Instrumentation showed the bonus net wins on cascade *selection and timing*,
 * not volume (identical ~9.7 bonus marks/game vs the control) — so this block
 * encodes where bonuses LAND rather than how many exist:
 *  - 1: orange write-landing potential — every unfired write→orange bonus
 *    valued at (value/6) × (next open slot's multiplier/3) × its proximity².
 *  - 1: purple write-landing potential (same, multiplier-free).
 *  - 1: multiplier of orange's slot AFTER next (/3) — filling one orange slot
 *    with a die shifts where a granted 6 lands; the net can time the ×3.
 *  - 5: per-area depth-2 "cascade fuse" — a one-away group in A while a
 *    one-away bonus elsewhere grants a mark into A.
 *  - 1: fox fuse — a one-away fox × current minimum area (/40): a fox is
 *    worth the final min area, so its chase value is state-dependent.
 */
export const TD_BONUS3_FEATURES = TD_BONUS_FEATURES + 9;

interface BonusSite {
  area: string;
  /** Group cell indices, or null for a track slot site. */
  cells: number[] | null;
  /** Track slot index when cells is null. */
  slot: number;
  markTargets: string[];
  write: { area: string; value: number } | null;
  isFox: boolean;
}

const siteCache = new WeakMap<VariantDef, BonusSite[]>();

function markTargetsOf(e: Effect): string[] {
  switch (e.t) {
    case 'crossAny':
    case 'crossNext':
    case 'free':
      return [e.area];
    case 'choice':
      return e.options.flatMap(markTargetsOf);
    default:
      return [];
  }
}

function sitesOf(v: VariantDef): BonusSite[] {
  let sites = siteCache.get(v);
  if (sites) return sites;
  sites = [];
  for (const area of v.areas) {
    const ui = area.ui;
    if (ui.groups) {
      for (const g of ui.groups) {
        if (!g.bonus) continue;
        sites.push({
          area: area.id,
          cells: g.cells,
          slot: -1,
          markTargets: markTargetsOf(g.bonus),
          write: g.bonus.t === 'writeNext' ? { area: g.bonus.area, value: g.bonus.value } : null,
          isFox: g.bonus.t === 'fox',
        });
      }
    }
    ui.cells.forEach((c, i) => {
      if (!c.bonus) return;
      sites!.push({
        area: area.id,
        cells: null,
        slot: i,
        markTargets: markTargetsOf(c.bonus),
        write: c.bonus.t === 'writeNext' ? { area: c.bonus.area, value: c.bonus.value } : null,
        isFox: c.bonus.t === 'fox',
      });
    });
  }
  siteCache.set(v, sites);
  return sites;
}

/** Proximity of an unfired site in [0, 1]; 0 when fired (banked already). */
function siteProximity(s: GameState, site: BonusSite): number {
  const cells = s.areas[site.area];
  if (site.cells) {
    let done = 0;
    for (const c of site.cells) if (cells[c] !== 0) done++;
    if (done === site.cells.length) return 0;
    const frac = done / site.cells.length;
    return frac * frac;
  }
  if (cells[site.slot] !== 0) return 0;
  let next = 0;
  while (next < cells.length && cells[next] !== 0) next++;
  return 1 / (1 + (site.slot - next));
}

export function extractFeaturesBonus3(s: GameState, v: VariantDef, x: Float64Array): void {
  extractFeaturesBonus(s, v, x); // zero-fills, writes [0, TD_BONUS_FEATURES)
  const k = TD_BONUS_FEATURES;
  const sites = sitesOf(v);
  const br = scoreState(s, v);

  const orange = v.areas.find((a) => a.id === 'orange');
  const multAt = (offset: number): number => {
    if (!orange) return 0;
    const cells = s.areas.orange;
    let next = 0;
    while (next < cells.length && cells[next] !== 0) next++;
    const i = next + offset;
    if (i >= cells.length) return 0;
    const lbl = orange.ui.cells[i].label;
    return lbl ? Number(lbl.replace('×', '')) || 1 : 1;
  };

  // Per-area one-away counts (groups) + near track sites, for the fuses.
  const oneAwayIn: Record<string, number> = {};
  const oneAwayGiversInto: Record<string, number> = {};
  let foxOneAway = 0;
  for (const site of sites) {
    const cells = s.areas[site.area];
    let oneAway = false;
    if (site.cells) {
      let done = 0;
      for (const c of site.cells) if (cells[c] !== 0) done++;
      oneAway = done === site.cells.length - 1;
      if (oneAway) oneAwayIn[site.area] = (oneAwayIn[site.area] ?? 0) + 1;
    } else if (cells[site.slot] === 0) {
      let next = 0;
      while (next < cells.length && cells[next] !== 0) next++;
      oneAway = site.slot === next;
    }
    if (!oneAway) continue;
    if (site.isFox) foxOneAway++;
    for (const t of site.markTargets) {
      oneAwayGiversInto[t] = (oneAwayGiversInto[t] ?? 0) + 1;
    }
  }

  // Write-landing potentials.
  let orangePot = 0;
  let purplePot = 0;
  for (const site of sites) {
    if (!site.write) continue;
    const prox = siteProximity(s, site);
    if (prox === 0) continue;
    if (site.write.area === 'orange') orangePot += (site.write.value / 6) * (multAt(0) / 3) * prox;
    else if (site.write.area === 'purple') purplePot += (site.write.value / 6) * prox;
  }
  x[k] = Math.min(1, orangePot);
  x[k + 1] = Math.min(1, purplePot);
  x[k + 2] = multAt(1) / 3;

  const AREAS = ['yellow', 'blue', 'green', 'orange', 'purple'];
  for (let i = 0; i < 5; i++) {
    const a = AREAS[i];
    x[k + 3 + i] = Math.min(1, (oneAwayIn[a] ?? 0) * 0.5) * Math.min(1, (oneAwayGiversInto[a] ?? 0) * 0.5);
  }
  x[k + 8] = Math.min(1, foxOneAway) * (br.minArea / 40);
}

// ---------------------------------------------------------------------------
// v1bonus2: reachability-gated track bonuses + time-bucketed chase signals
// ---------------------------------------------------------------------------

/**
 * The refinement hypotheses: (1) late track bonuses (green/orange/purple) are
 * only worth chasing when they are *reachable* in the rounds that remain, and
 * (2) the order of bonus acquisition matters — the same one-away signal means
 * different things in round 1 and round 6. This block appends:
 *  - 3: per-track reachability of the next bonus-carrying slot —
 *    1 - clamp(distance / roundsLeft) — so far-off bonuses go dark late.
 *  - 24: the 8 one-away kind channels copied into an early/mid/late bucket.
 *  - 6: banked reroll/+1 unlock fractions in the same three buckets.
 */
export const TD_BONUS2_FEATURES = TD_BONUS_FEATURES + 33;

export function extractFeaturesBonus2(s: GameState, v: VariantDef, x: Float64Array): void {
  extractFeaturesBonus(s, v, x); // zero-fills, writes [0, TD_BONUS_FEATURES)
  const k = TD_BONUS_FEATURES;
  const roundsLeft = Math.max(1, v.rounds - s.round + 1);
  const bucket = s.round <= 2 ? 0 : s.round <= 4 ? 1 : 2;

  // Per-track reachability of the next bonus slot (up to 3 tracks).
  let ti = 0;
  for (const area of v.areas) {
    if (area.ui.kind !== 'track' || ti >= 3) continue;
    const cells = s.areas[area.id];
    const next = cells.findIndex((c) => c === 0);
    if (next >= 0) {
      for (let i = next; i < area.ui.cells.length; i++) {
        if (!area.ui.cells[i].bonus) continue;
        x[k + ti] = Math.max(0, 1 - (i - next) / roundsLeft);
        break;
      }
    }
    ti++;
  }

  // One-away channels by game phase: same signal, different meaning per era.
  const oneAway = TD_FEATURES + 3;
  for (let c = 0; c < 8; c++) x[k + 3 + bucket * 8 + c] = x[oneAway + c];

  // Banked unlocks by game phase (early unlocks compound, late ones do not).
  x[k + 27 + bucket] = x[TD_FEATURES];
  x[k + 30 + bucket] = x[TD_FEATURES + 1];
}

// ---------------------------------------------------------------------------
// Value-based policy (v1's argmax machinery over the bonus encoding)
// ---------------------------------------------------------------------------

/** V(state) on the score/300 scale; terminal states use the real score. */
export function stateValueBonus(ctx: EvalCtx, s: GameState, v: VariantDef): number {
  if (s.phase === 'over') return scoreState(s, v).total / 300;
  extractFeaturesBonus(s, v, ctx.x);
  return forward(ctx.net, ctx.x, ctx.h1, ctx.h2);
}

/** Resolve queued bonus decisions by one-step V argmax. */
export function resolvePendingByValueBonus(ctx: EvalCtx, s: GameState, v: VariantDef): GameState {
  let cur = s;
  let guard = 0;
  while (cur.pending.length > 0 && guard++ < 64) {
    const node = getPending(cur, v);
    if (node.kind !== 'decision') break;
    let best: GameState | null = null;
    let bestVal = -Infinity;
    for (const a of node.actions) {
      const ns = applyAction(cur, v, a);
      const val = stateValueBonus(ctx, ns, v);
      if (val > bestVal) {
        bestVal = val;
        best = ns;
      }
    }
    if (!best) break;
    cur = best;
  }
  return cur;
}

/** Afterstate argmax over V; the policy for td-net-bonus and its trainer. */
export function chooseByValueBonus(
  ctx: EvalCtx,
  s: GameState,
  v: VariantDef,
  actions: Action[],
): Action {
  let best = actions[0];
  let bestVal = -Infinity;
  for (const a of actions) {
    const ns = resolvePendingByValueBonus(ctx, applyAction(s, v, a), v);
    const val = stateValueBonus(ctx, ns, v);
    if (val > bestVal) {
      bestVal = val;
      best = a;
    }
  }
  return best;
}

/** V/resolve/choose over the bonus3 encoding. */
export function stateValueBonus3(ctx: EvalCtx, s: GameState, v: VariantDef): number {
  if (s.phase === 'over') return scoreState(s, v).total / 300;
  extractFeaturesBonus3(s, v, ctx.x);
  return forward(ctx.net, ctx.x, ctx.h1, ctx.h2);
}

export function resolvePendingByValueBonus3(ctx: EvalCtx, s: GameState, v: VariantDef): GameState {
  let cur = s;
  let guard = 0;
  while (cur.pending.length > 0 && guard++ < 64) {
    const node = getPending(cur, v);
    if (node.kind !== 'decision') break;
    let best: GameState | null = null;
    let bestVal = -Infinity;
    for (const a of node.actions) {
      const ns = applyAction(cur, v, a);
      const val = stateValueBonus3(ctx, ns, v);
      if (val > bestVal) {
        bestVal = val;
        best = ns;
      }
    }
    if (!best) break;
    cur = best;
  }
  return cur;
}

export function chooseByValueBonus3(
  ctx: EvalCtx,
  s: GameState,
  v: VariantDef,
  actions: Action[],
): Action {
  let best = actions[0];
  let bestVal = -Infinity;
  for (const a of actions) {
    const ns = resolvePendingByValueBonus3(ctx, applyAction(s, v, a), v);
    const val = stateValueBonus3(ctx, ns, v);
    if (val > bestVal) {
      bestVal = val;
      best = a;
    }
  }
  return best;
}

/** V/resolve/choose over the bonus2 encoding (mirrors the trio above). */
export function stateValueBonus2(ctx: EvalCtx, s: GameState, v: VariantDef): number {
  if (s.phase === 'over') return scoreState(s, v).total / 300;
  extractFeaturesBonus2(s, v, ctx.x);
  return forward(ctx.net, ctx.x, ctx.h1, ctx.h2);
}

export function resolvePendingByValueBonus2(ctx: EvalCtx, s: GameState, v: VariantDef): GameState {
  let cur = s;
  let guard = 0;
  while (cur.pending.length > 0 && guard++ < 64) {
    const node = getPending(cur, v);
    if (node.kind !== 'decision') break;
    let best: GameState | null = null;
    let bestVal = -Infinity;
    for (const a of node.actions) {
      const ns = applyAction(cur, v, a);
      const val = stateValueBonus2(ctx, ns, v);
      if (val > bestVal) {
        bestVal = val;
        best = ns;
      }
    }
    if (!best) break;
    cur = best;
  }
  return cur;
}

export function chooseByValueBonus2(
  ctx: EvalCtx,
  s: GameState,
  v: VariantDef,
  actions: Action[],
): Action {
  let best = actions[0];
  let bestVal = -Infinity;
  for (const a of actions) {
    const ns = resolvePendingByValueBonus2(ctx, applyAction(s, v, a), v);
    const val = stateValueBonus2(ctx, ns, v);
    if (val > bestVal) {
      bestVal = val;
      best = a;
    }
  }
  return best;
}

// ---------------------------------------------------------------------------
// Strategy factory
// ---------------------------------------------------------------------------

export interface TdNetBonusOpts {
  params?: TdNetParams;
  name?: string;
}

/** Leaf evaluation on the score scale, for expectimax's `evalFn`. */
export function makeTdNetBonusEval(params?: TdNetParams): (s: GameState, v: VariantDef) => number {
  const ctx = createEvalCtx(netFromParams(params ?? TDNET_BONUS_WEIGHTS));
  return (s, v) => 300 * stateValueBonus(ctx, s, v);
}

export function makeTdNetBonus(opts: TdNetBonusOpts = {}): Strategy {
  const ctx = createEvalCtx(netFromParams(opts.params ?? TDNET_BONUS_WEIGHTS));
  return {
    name: opts.name ?? 'td-net-bonus',
    choose(state, actions, c) {
      if (actions.length === 1) return actions[0];
      return chooseByValueBonus(ctx, state, c.variant, actions);
    },
  };
}
